#MenuTitle: Rename Gujarati glyphs for the AFDKO Workflow
# -*- encoding: utf-8

def main():

  Glyphs.font.disableUpdateInterface()
  Glyphs.clearLog()
  Glyphs.showMacroWindow()

  print "Renaming glyphs for the for the GlyphsApp Workflow..."

  for g in Glyphs.font.glyphs:
    if g.name in Glyphs_to_new_dict.keys():
      g.name = Glyphs_to_new_dict[g.name]

  print "Done!"
  Glyphs.font.enableUpdateInterface()

# - - -

Glyphs_to_new_dict = {
"aamatra-gurmukhi": "grmAA",
"imatra-gurmukhi": "grmI",
"iimatra-gurmukhi": "grmII",
"a-gurmukhi": "grA",
"aa-gurmukhi": "grAA",
"i-gurmukhi": "grI",
"ii-gurmukhi": "grII",
"u-gurmukhi": "grU",
"uu-gurmukhi": "grUU",
"ee-gurmukhi": "grEE",
"ai-gurmukhi": "grAI",
"oo-gurmukhi": "grOO",
"au-gurmukhi": "grAU",
"ka-gurmukhi": "grKA",
"kha-gurmukhi": "grKHA",
"ga-gurmukhi": "grGA",
"gha-gurmukhi": "grGHA",
"nga-gurmukhi": "grNGA",
"ca-gurmukhi": "grCA",
"cha-gurmukhi": "grCHA",
"ja-gurmukhi": "grJA",
"jha-gurmukhi": "grJHA",
"nya-gurmukhi": "grNYA",
"tta-gurmukhi": "grTTA",
"ttha-gurmukhi": "grTTHA",
"dda-gurmukhi": "grDDA",
"ddha-gurmukhi": "grDDHA",
"nna-gurmukhi": "grNNA",
"ta-gurmukhi": "grTA",
"tha-gurmukhi": "grTHA",
"da-gurmukhi": "grDA",
"dha-gurmukhi": "grDHA",
"na-gurmukhi": "grNA",
"pa-gurmukhi": "grPA",
"pha-gurmukhi": "grPHA",
"ba-gurmukhi": "grBA",
"bha-gurmukhi": "grBHA",
"ma-gurmukhi": "grMA",
"ya-gurmukhi": "grYA",
"ra-gurmukhi": "grRA",
"la-gurmukhi": "grLA",
"lla-gurmukhi": "grLxA",
"va-gurmukhi": "grVA",
"sha-gurmukhi": "grSxA",
"sa-gurmukhi": "grSA",
"ha-gurmukhi": "grHA",
"khha-gurmukhi": "grKHxA",
"ghha-gurmukhi": "grGxA",
"za-gurmukhi": "grJxA",
"rra-gurmukhi": "grRRA",
"fa-gurmukhi": "grPHxA",
"iri-gurmukhi": "grIri",
"ura-gurmukhi": "grUra",
"ekonkar-gurmukhi": "grEkonkar",
"zero-gurmukhi": "grZero",
"one-gurmukhi": "grOne",
"two-gurmukhi": "grTwo",
"three-gurmukhi": "grThree",
"four-gurmukhi": "grFour",
"five-gurmukhi": "grFive",
"six-gurmukhi": "grSix",
"seven-gurmukhi": "grSeven",
"eight-gurmukhi": "grEight",
"nine-gurmukhi": "grNine",
"adakbindi-gurmukhi": "grAdakbindi",
"bindi-gurmukhi": "grBindi",
"nukta-gurmukhi": "grNukta",
"umatra-gurmukhi": "grmU",
"umatra-gurmukhi.alt": "grmU.alt",
"umatra-gurmukhi.alt1": "grmU.alt1",
"umatra-gurmukhi.alt2": "grmU.alt2",
"umatra-gurmukhi.alt3": "grmU.alt3",
"uumatra-gurmukhi": "grmU",
"uumatra-gurmukhi.alt": "grmUU.alt",
"uumatra-gurmukhi.alt1": "grmUU.alt1",
"uumatra-gurmukhi.alt2": "grmUU.alt2",
"uumatra-gurmukhi.alt3": "grmUU.alt3",
"eematra-gurmukhi": "grmEE",
"aimatra-gurmukhi": "grmAI",
"oomatra-gurmukhi": "grmOO",
"oomatra-gurmukhi.alt": "grmOO.alt",
"oomatra-gurmukhi.alt1": "grmOO.alt1",
"oomatra-gurmukhi.alt2": "grmOO.alt2",
"oomatra-gurmukhi.alt3": "grmOO.alt3",
"aumatra-gurmukhi": "grmAU",
"halant-gurmukhi": "grVirama",
"udaat-gurmukhi": "grYakash",
"tippi-gurmukhi": "grTippi",
"tippi-gurmukhi.alt": "grTippi.alt",
"tippi-gurmukhi.alt1": "grTippi.alt1",
"addak-gurmukhi": "grAddak",
"addak-gurmukhi.alt": "grAddak.alt",
"addak-gurmukhi.alt1": "grAddak.alt1",
"udaat-gurmukhi": "grUdaat",
"visarga-gurmukhi": "grVisarga",
"r-gurmukhi.sub": "grRAc2",
"v-gurmukhi.sub": "grVAc2",
"h-gurmukhi.sub": "grHAc2",
"y-gurmukhi.sub": "grYAc2",
"k_ra-gurmukhi": "grKA_RAc2",
"kh_ra-gurmukhi": "grKHA_RAc2",
"g_ra-gurmukhi": "grGA_RAc2",
"gh_ra-gurmukhi": "grGHA_RAc2",
"ng_ra-gurmukhi": "grNGA_RAc2",
"c_ra-gurmukhi": "grCA_RAc2",
"ch_ra-gurmukhi": "grCHA_RAc2",
"j_ra-gurmukhi": "grJA_RAc2",
"jh_ra-gurmukhi": "grJHA_RAc2",
"ny_ra-gurmukhi": "grNYA_RAc2",
"tta_ra-gurmukhi": "grTTA_RAc2",
"tth_ra-gurmukhi": "grTTHA_RAc2",
"dd_ra-gurmukhi": "grDDA_RAc2",
"ddh_ra-gurmukhi": "grDDHA_RAc2",
"nn_ra-gurmukhi": "grNNA_RAc2",
"t_ra-gurmukhi": "grTA_RAc2",
"th_ra-gurmukhi": "grTHA_RAc2",
"d_ra-gurmukhi": "grDA_RAc2",
"dh_ra-gurmukhi": "grDHA_RAc2",
"n_ra-gurmukhi": "grNA_RAc2",
"p_ra-gurmukhi": "grPA_RAc2",
"ph_ra-gurmukhi": "grPHA_RAc2",
"b_ra-gurmukhi": "grBA_RAc2",
"bh_ra-gurmukhi": "grBHA_RAc2",
"m_ra-gurmukhi": "grMA_RAc2",
"y_ra-gurmukhi": "grYA_RAc2",
"r_ra-gurmukhi": "grRA_RAc2",
"l_ra-gurmukhi": "grLA_RAc2",
"v_ra-gurmukhi": "grVA_RAc2",
"s_ra-gurmukhi": "grSA_RAc2",
"h_ra-gurmukhi": "grHA_RAc2",
"rr_ra-gurmukhi": "grRRA_RAc2",
"khha-gurmukhi": "grKHxA_RAc2",
"ghh_ra-gurmukhi": "grGxA_RAc2",
"z_ra-gurmukhi": "grJxA_RAc2",
"f_ra-gurmukhi": "grPHxA_RAc2",
"ll_ra-gurmukhi": "grLxA_RAc2",
"sh_ra-gurmukhi": "grSxA_RAc2",
"iimatra_bindi-gurmukhi": "grmII_Bindi",
"eematra_bindi-gurmukhi": "grmEE_Bindi",
"aimatra_bindi-gurmukhi": "grmAI_Bindi",
"oomatra_bindi-gurmukhi": "grmOO_Bindi",
"aumatra_bindi-gurmukhi": "grmAU_Bindi",
"headline-gurmukhi": "grHeadline",
"headline_bindi-gurmukhi": "grHeadline_Bindi",
"headline_visarga-gurmukhi": "grHeadline_Visarga",
"headline_addak-gurmukhi": "grHeadline_Addak",
}

if __name__ == "__main__":
  main()
